# Generated by Django 2.1.9 on 2019-09-01 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid', models.CharField(max_length=255, unique='true')),
                ('sex', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=25)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('date_naissance', models.DateField()),
                ('photo', models.ImageField(blank='true', null='true', upload_to='clients')),
                ('telephone', models.CharField(blank=True, max_length=10, null='true')),
                ('telephone_urgence', models.CharField(blank=True, max_length=10, null='true')),
                ('adresse', models.CharField(blank=True, max_length=255, null='true')),
                ('email', models.EmailField(blank=True, max_length=70, null='true')),
                ('seance', models.PositiveIntegerField(default=0)),
                ('date_debut', models.DateField(auto_now_add=True)),
                ('date_fin', models.DateField(auto_now_add=True)),
                ('credit', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
