# Generated by Django 2.1.9 on 2019-09-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forfait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('nbr_seance', models.PositiveIntegerField()),
                ('prix', models.PositiveIntegerField()),
            ],
        ),
    ]
