# Generated by Django 2.1.9 on 2019-10-09 01:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank='true', default=datetime.datetime.now)),
                ('ouverture', models.IntegerField(blank='true', default=0)),
                ('fermeture', models.IntegerField(blank='true', null=True)),
                ('fermeture_prevu', models.IntegerField(blank='true', default=0)),
            ],
        ),
    ]
